import type { Metadata } from "next";
import { Work_Sans} from "next/font/google";
import "./globals.css";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tjønnås Delikatesser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="body"
        className={`${workSans.variable} noscroll antialiased h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
