/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProductItem = {
  _id: string;
  _type: "productItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  productName?: string;
  slug?: Slug;
  category?: string;
  lead?: string;
  price?: number;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  inStock?: boolean;
};

export type MenuItem = {
  _id: string;
  _type: "menuItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  categoriTitle?: string;
  name?: string;
  price?: string;
  description?: string;
  conditionalPrice?: string;
  housePick?: boolean;
};

export type MenuCategory = {
  _id: string;
  _type: "menuCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nameOfMenu?: "tjonnasdelikatesser" | "norvald" | "catering";
  menuItems?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "menuItem";
  }>;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = ProductItem | MenuItem | MenuCategory | Menu | Event | Post | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../tjonnas-website/app/menu/page.tsx
// Variable: TJONNAS_QUERY
// Query: *[_type=="menu" && nameOfMenu =="tjonnasdelikatesser"] {  _id,  nameOfMenu,  menuItems[] -> {      _id,       conditionalPrice,         name,      categoriTitle,      description,      housePick,      price       },}
export type TJONNAS_QUERYResult = Array<{
  _id: string;
  nameOfMenu: "catering" | "norvald" | "tjonnasdelikatesser" | null;
  menuItems: Array<{
    _id: string;
    conditionalPrice: string | null;
    name: string | null;
    categoriTitle: string | null;
    description: string | null;
    housePick: boolean | null;
    price: string | null;
  }> | null;
}>;
// Variable: CATERING_QUERY
// Query: *[_type=="menu" && nameOfMenu =="catering"] {  _id,  nameOfMenu,  menuItems[] -> {      _id,       conditionalPrice,         name,      categoriTitle,      description,      housePick,      price       },}
export type CATERING_QUERYResult = Array<{
  _id: string;
  nameOfMenu: "catering" | "norvald" | "tjonnasdelikatesser" | null;
  menuItems: Array<{
    _id: string;
    conditionalPrice: string | null;
    name: string | null;
    categoriTitle: string | null;
    description: string | null;
    housePick: boolean | null;
    price: string | null;
  }> | null;
}>;
// Variable: NORVALD_QUERY
// Query: *[_type=="menu" && nameOfMenu =="norvald"] {  _id,  nameOfMenu,  menuItems[] -> {      _id,       conditionalPrice,         name,      categoriTitle,      description,      housePick,      price       },}
export type NORVALD_QUERYResult = Array<{
  _id: string;
  nameOfMenu: "catering" | "norvald" | "tjonnasdelikatesser" | null;
  menuItems: Array<{
    _id: string;
    conditionalPrice: string | null;
    name: string | null;
    categoriTitle: string | null;
    description: string | null;
    housePick: boolean | null;
    price: string | null;
  }> | null;
}>;

// Source: ../tjonnas-website/app/products/[slug]/page.tsx
// Variable: PRODUCT_QUERY
// Query: *[  _type == "productItem" &&  slug.current == $slug][0]
export type PRODUCT_QUERYResult = {
  _id: string;
  _type: "productItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  productName?: string;
  slug?: Slug;
  category?: string;
  lead?: string;
  price?: number;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  inStock?: boolean;
} | null;

// Source: ../tjonnas-website/app/products/page.tsx
// Variable: PRODUCTS_QUERY
// Query: *[_type=="productItem"]
export type PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "productItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  productName?: string;
  slug?: Slug;
  category?: string;
  lead?: string;
  price?: number;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  inStock?: boolean;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type==\"menu\" && nameOfMenu ==\"tjonnasdelikatesser\"] {\n  _id,\n  nameOfMenu,\n  menuItems[] -> {\n      _id,\n       conditionalPrice,\n         name,\n      categoriTitle,\n      description,\n      housePick,\n      price     \n  },\n}\n": TJONNAS_QUERYResult;
    "*[_type==\"menu\" && nameOfMenu ==\"catering\"] {\n  _id,\n  nameOfMenu,\n  menuItems[] -> {\n      _id,\n       conditionalPrice,\n         name,\n      categoriTitle,\n      description,\n      housePick,\n      price     \n  },\n}\n": CATERING_QUERYResult;
    "*[_type==\"menu\" && nameOfMenu ==\"norvald\"] {\n  _id,\n  nameOfMenu,\n  menuItems[] -> {\n      _id,\n       conditionalPrice,\n         name,\n      categoriTitle,\n      description,\n      housePick,\n      price     \n  },\n}\n": NORVALD_QUERYResult;
    "*[\n  _type == \"productItem\" &&\n  slug.current == $slug\n][0]": PRODUCT_QUERYResult;
    "*[_type==\"productItem\"]": PRODUCTS_QUERYResult;
  }
}
